name: Integrated Testing - No broken code!

on:  
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      # Installing requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./Cloud/2-automation_principles/1_api_automations/3_countryinfo_travelers/requirements.txt
      # Running the integration tests 
      - name: Running Integration Tests
        run: |
          pip install pytest pytest-cov
          python -m pytest ./Cloud/2-automation_principles/1_api_automations/3_countryinfo_travelers/tests/shared_tests.py
